### ISSUE TITLE
Setup environment

### ISSUE THREAD

**Issue by masmangan** [MS-2017-2/SoundRecorder#1]
AGES machines.
Eclipse Che.

**Comment by MatheusVaccaro** [comment]
Poderemos utilizar a sala ao lado da AGES e os notebooks durante a aula.
As máquinas da AGES possuem o Android Studio instalado.
O Eclipse pode ser utilizado como alternativa para o Android Studio, mas é preciso instalar alguns plug-ins para fazê-lo funcionar. Mesmo assim, o Android Studio é preferível ao Eclipse.
https://developer.android.com/studio/index.html?hl=pt-br

**Comment by masmangan** [comment]
Android Studio is not installed on AGES 24.

**Comment by masmangan** [comment]
Opção sugerida: utilizar notebooks pessoais.
Notebooks da AGES permanecem como alternativa.
Virtualização do Eclipse Che e outros deve ser ainda investigada.
