### ISSUE TITLE
Create a first GUI test using Espresso or similar framework

### ISSUE THREAD

**Issue by masmangan** [MS-2017-2/SoundRecorder#18]
See:
https://developer.android.com/training/testing/ui-testing/espresso-testing.html

**Comment by masmangan** [comment]
Related to #17

**Comment by lima-eduardo** [comment]
Created first UI test (US04 from #12) in Java and using:
- Appium: http://appium.io/
- Selenium: http://www.seleniumhq.org/

Maven Project: https://github.com/lima-eduardo/SoundRecorderUITests
