### ISSUE TITLE
Class diagram from source code

### ISSUE THREAD

**Issue by masmangan** [MS-2017-2/SoundRecorder#2]

**Comment by caioilha** [comment]
![classessoundrecorder](https://user-images.githubusercontent.com/13875869/30329192-fb32118e-97a7-11e7-87ff-6a4f639953d8.png)
Fiz a engenharia reversa com o 'Enterprise Architect" mas ficaram umas classes perdidas. Assim que der tento fazer no Astah p/ ver se ele não consegue ser um guia melhor para as classes.

**Comment by masmangan** [comment]
Problemas encontrados:
a) necessário conhecimento da plataforma para completar informação ausente no diagrama, ex., configurações em XML e formulários em XML.
b) é necessário agrupar os componentes para facilitar a compreensão.
Informações relevantes:
a) aplicação de pequeno porte
b) abstrações principais: Recording, FileViewer e DBHelper

**Comment by masmangan** [comment]
O trabalho de compreensão com diagramas continua no #3.
