### ISSUE TITLE
Requirements from screenshots and/or source code

### ISSUE THREAD

**Issue by masmangan** [MS-2017-2/SoundRecorder#4]

**Comment by MatheusVaccaro** [comment]
![about](https://user-images.githubusercontent.com/14074196/30244090-a4717a7c-958d-11e7-9960-08903341e151.png)
![settings](https://user-images.githubusercontent.com/14074196/30244089-a47004a8-958d-11e7-8bcf-b36624b1454d.png)
![delete record](https://user-images.githubusercontent.com/14074196/30244092-a476bf5a-958d-11e7-8558-c5525971246e.png)
![share record](https://user-images.githubusercontent.com/14074196/30244091-a47643cc-958d-11e7-8525-0e58f190c619.png)
![rename record](https://user-images.githubusercontent.com/14074196/30244093-a4778d54-958d-11e7-96ce-50e5d1c15467.png)
![record editting options](https://user-images.githubusercontent.com/14074196/30244094-a48391ee-958d-11e7-97c4-45ca4e49a0e7.png)
![records list](https://user-images.githubusercontent.com/14074196/30244095-a491aacc-958d-11e7-96cc-388afdab290b.png)
![record](https://user-images.githubusercontent.com/14074196/30244096-a4adc6e4-958d-11e7-9f2c-b8172ddbd89f.png)

**Comment by MatheusVaccaro** [comment]
Start Recording
![record](https://user-images.githubusercontent.com/14074196/30244101-c2c1b8a2-958d-11e7-9d78-55f4313109af.png)

**Comment by MatheusVaccaro** [comment]
List Records
![records list](https://user-images.githubusercontent.com/14074196/30244123-2e37fee8-958e-11e7-912f-f18403c0075f.png)

**Comment by MatheusVaccaro** [comment]
Record editting options
![record editting options](https://user-images.githubusercontent.com/14074196/30244119-24c4bf4a-958e-11e7-8ecc-cf866e9b3da4.png)

**Comment by MatheusVaccaro** [comment]
Share a Record
![share record](https://user-images.githubusercontent.com/14074196/30244127-46e7e7aa-958e-11e7-813d-ba5782041645.png)

**Comment by MatheusVaccaro** [comment]
Rename a Record
![rename record](https://user-images.githubusercontent.com/14074196/30244133-64c17192-958e-11e7-988d-e2e6dfc7f050.png)

**Comment by MatheusVaccaro** [comment]
Delete a Record
![delete record](https://user-images.githubusercontent.com/14074196/30244137-6dcc3920-958e-11e7-8527-3a6b0cd31993.png)

**Comment by MatheusVaccaro** [comment]
App settings. The user can turn on High Quality Recordings and see About the App.
![settings](https://user-images.githubusercontent.com/14074196/30244139-834725e4-958e-11e7-9823-e17a080a5d10.png)

**Comment by MatheusVaccaro** [comment]
About Screen
![about](https://user-images.githubusercontent.com/14074196/30244140-8958fd22-958e-11e7-9421-3dfbf6914276.png)

**Comment by MatheusVaccaro** [comment]
There are no Tests implemented.
