### ISSUE TITLE
Commit reporting from GitHub

### ISSUE THREAD

**Issue by masmangan** [MS-2017-2/SoundRecorder#6]

**Comment by lima-eduardo** [comment]
#### Change - Author - Date
Initial commit - dkim0419 - 24/12/14
Added SQLite database and views to to see saved recordings - dkim0419 - 31/12/14
Added long click to delete recording - dkim0419 - 01/01/15
Prevent screen tunning off during media playback and audio record - dkim0419 - 04/01/15
Functionality to rename files - dkim0419 - 06/01/16
Share record feature - andrewgaul - 29/06/16
Name recordings with timestamp - andrewgaul - 30/06/16
Rename file while renaming recording - andrewgaul - 30/06/16
Menu item for high quality recording - ChristophHaag - 22/05/17
Settings activity with hq option - dkim0419 - 22/05/17

**Comment by masmangan** [comment]
O registro revela responsáveis pela evolução da aplicação.
É possível encontrar indícios de duas leis de Lehman: mudança constante e aumento de complexidade.
